# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."dockge" = {
    image = "louislam/dockge:latest";
    volumes = [
      "/var/lib/dockge/config:/app/data:rw"
      "/opt/stacks:/opt/stacks:rw"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [
      "5001:5001/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dockge"
      "--network=dockge_default"
    ];
  };
  systemd.services."docker-dockge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-dockge_default.service"
    ];
    requires = [
      "docker-network-dockge_default.service"
    ];
    partOf = [
      "docker-compose-dockge-root.target"
    ];
    wantedBy = [
      "docker-compose-dockge-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-dockge_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f dockge_default";
    };
    script = ''
      docker network inspect dockge_default || docker network create dockge_default
    '';
    partOf = [ "docker-compose-dockge-root.target" ];
    wantedBy = [ "docker-compose-dockge-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-dockge-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
